set shell := ["bash", "-cu"]

default: check

fmt:
    cargo fmt --all

fmt-check:
    cargo fmt --all -- --check

check:
    cargo check --all-targets

clippy:
    cargo clippy --all-targets -- -D warnings

test:
    cargo test --all-targets

ci: fmt-check check clippy test

run *args:
    cargo run -- {{args}}

doctor:
    cargo run -- doctor
