[package]
name = "pire-builtins"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["http"]
http = ["dep:reqwest"]

[dependencies]
hex.workspace = true
pire-core.workspace = true
reqwest = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
shlex.workspace = true
thiserror.workspace = true
wait-timeout.workspace = true
walkdir.workspace = true

[lints]
workspace = true
